const consultationRepository = require('../../infrastructure/repositories/consultation.repository');
const appointmentRepository = require('../../infrastructure/repositories/appointment.repository');
const { ConsultationMessage } = require('../../infrastructure/database');
const jitsiService = require('../../infrastructure/services/jitsi.service');
const emailService = require('./email.service');
const { ConsultationStatus } = require('../../domain/enums/consultation-status.enum');
const { ConsultationType } = require('../../domain/enums/consultation-type.enum');
const { AppointmentStatus } = require('../../domain/enums/appointment-status.enum');

/**
 * Consultation Service
 * Business logic for video consultation lifecycle management
 */

class ConsultationService {

    /**
     * Create a consultation for a confirmed VIDEO appointment
     * Called automatically when a payment is successful
     * @param {number} appointmentId
     * @returns {Promise<object|null>} Created consultation, or null for non-video
     */
    async createConsultation(appointmentId) {
        const appointment = await appointmentRepository.findAppointmentById(appointmentId);

        if (!appointment) {
            const err = new Error('Appointment not found');
            err.statusCode = 404;
            throw err;
        }

        const consultType = Number(appointment.consultationType);

        // Only create for VIDEO or EMAIL consultations
        if (consultType !== ConsultationType.VIDEO && consultType !== ConsultationType.EMAIL) {
            return null;
        }

        // Idempotency guard — don't double-create
        const existing = await consultationRepository.findByAppointmentId(appointmentId);
        if (existing) {
            return existing;
        }

        // Build room name — Jitsi for VIDEO, placeholder for EMAIL
        const roomName = consultType === ConsultationType.VIDEO
            ? jitsiService.createRoom(appointment)
            : `email-thread-${appointment.publicId || appointmentId}`;

        // Persist consultation (meetingToken auto-generated by model default)
        const consultation = await consultationRepository.create({ appointmentId, roomName });

        // Build link to consulting page
        const preJoinUrl = `${process.env.FRONTEND_URL || 'http://localhost:5173'}/consulting`;

        // Send invite to patient and doctor
        await emailService.sendConsultationInvite(appointment.patient.user, appointment, preJoinUrl);
        await emailService.sendConsultationInvite(appointment.doctor.user, appointment, preJoinUrl);

        return consultation;
    }

    /**
     * Start a consultation session (doctor only) — by consultation ID
     * @param {number} consultationId
     * @param {number} userId - Must be the doctor's userId
     * @returns {Promise<object>} Updated consultation
     */
    async startConsultation(consultationId, userId) {
        const consultation = await consultationRepository.findById(consultationId);

        if (!consultation) {
            const err = new Error('Consultation not found');
            err.statusCode = 404;
            throw err;
        }

        if (consultation.appointment.doctor.userId !== userId) {
            const err = new Error('Only the assigned doctor can start this consultation');
            err.statusCode = 403;
            throw err;
        }

        if (consultation.status === ConsultationStatus.ENDED) {
            const err = new Error('Cannot restart an ended consultation');
            err.statusCode = 400;
            throw err;
        }

        return await consultationRepository.update(consultationId, {
            status: ConsultationStatus.ACTIVE,
            startedAt: new Date()
        });
    }

    /**
     * End a consultation session (doctor only) — by consultation ID
     * @param {number} consultationId
     * @param {number} userId - Must be the doctor's userId
     * @returns {Promise<object>} Updated consultation
     */
    async endConsultation(consultationId, userId) {
        const consultation = await consultationRepository.findById(consultationId);

        if (!consultation) {
            const err = new Error('Consultation not found');
            err.statusCode = 404;
            throw err;
        }

        if (consultation.appointment.doctor.userId !== userId) {
            const err = new Error('Only the assigned doctor can end this consultation');
            err.statusCode = 403;
            throw err;
        }

        // Update appointment status to COMPLETED
        await appointmentRepository.updateAppointment(consultation.appointmentId, {
            status: AppointmentStatus.COMPLETED
        });

        return await consultationRepository.update(consultationId, {
            status: ConsultationStatus.ENDED,
            endedAt: new Date()
        });
    }

    /**
     * Get Jitsi join info for a user (legacy — by appointmentPublicId)
     * @param {string} appointmentPublicId
     * @param {number} userId
     * @returns {Promise<object>} { domain, roomName, joinUrl, displayName }
     */
    async getJoinInfo(appointmentPublicId, userId) {
        const appointment = await appointmentRepository.findAppointmentByPublicId(appointmentPublicId);

        if (!appointment) {
            const err = new Error('Appointment not found');
            err.statusCode = 404;
            throw err;
        }

        const isPatient = appointment.patient.userId === userId;
        const isDoctor  = appointment.doctor.userId  === userId;

        if (!isPatient && !isDoctor) {
            const err = new Error('You are not a participant in this consultation');
            err.statusCode = 403;
            throw err;
        }

        const consultation = await consultationRepository.findByAppointmentId(appointment.id);

        if (!consultation) {
            const err = new Error('Consultation has not been created for this appointment. Please ensure the appointment is confirmed.');
            err.statusCode = 404;
            throw err;
        }

        const user = isPatient ? appointment.patient.user : appointment.doctor.user;
        return jitsiService.buildJoinInfo(user, consultation);
    }

    /**
     * Get consultation details by appointment ID
     * @param {number} appointmentId
     * @returns {Promise<object>} Consultation with documents
     */
    async getConsultationByAppointment(appointmentId) {
        const consultation = await consultationRepository.findByAppointmentId(appointmentId);

        if (!consultation) {
            const err = new Error('No consultation found for this appointment');
            err.statusCode = 404;
            throw err;
        }

        return consultation;
    }

    /**
     * Save a recording URL to the consultation
     * @param {number} consultationId
     * @param {number} userId - Must be the doctor's userId
     * @param {string} recordingUrl
     * @returns {Promise<object>} Updated consultation
     */
    async saveRecordingUrl(consultationId, userId, recordingUrl) {
        const consultation = await consultationRepository.findById(consultationId);

        if (!consultation) {
            const err = new Error('Consultation not found');
            err.statusCode = 404;
            throw err;
        }

        if (consultation.appointment.doctor.userId !== userId) {
            const err = new Error('Only the assigned doctor can save a recording');
            err.statusCode = 403;
            throw err;
        }

        if (!recordingUrl || !recordingUrl.startsWith('http')) {
            const err = new Error('A valid recording URL is required');
            err.statusCode = 400;
            throw err;
        }

        return await consultationRepository.update(consultationId, { recordingUrl });
    }

    /**
     * Save an uploaded document record
     * @param {number} consultationId
     * @param {number} userId - Uploader's userId
     * @param {object} fileInfo - { originalname, path, mimetype }
     * @returns {Promise<object>} Created document record
     */
    async uploadDocument(consultationId, userId, fileInfo) {
        const consultation = await consultationRepository.findById(consultationId);

        if (!consultation) {
            const err = new Error('Consultation not found');
            err.statusCode = 404;
            throw err;
        }

        const patientUserId = consultation.appointment.patient.userId;
        const doctorUserId  = consultation.appointment.doctor.userId;

        if (userId !== patientUserId && userId !== doctorUserId) {
            const err = new Error('You are not a participant in this consultation');
            err.statusCode = 403;
            throw err;
        }

        return await consultationRepository.addDocument({
            consultationId,
            fileName: fileInfo.originalname,
            filePath: fileInfo.path.replace(/\\/g, '/'),
            mimeType: fileInfo.mimetype,
            uploadedBy: userId
        });
    }

    /**
     * Get all documents for a consultation
     * @param {number} consultationId
     * @param {number} userId - Must be a participant
     * @returns {Promise<Array>}
     */
    async getDocuments(consultationId, userId) {
        const consultation = await consultationRepository.findById(consultationId);

        if (!consultation) {
            const err = new Error('Consultation not found');
            err.statusCode = 404;
            throw err;
        }

        const patientUserId = consultation.appointment.patient.userId;
        const doctorUserId  = consultation.appointment.doctor.userId;

        if (userId !== patientUserId && userId !== doctorUserId) {
            const err = new Error('You are not a participant in this consultation');
            err.statusCode = 403;
            throw err;
        }

        return await consultationRepository.getDocuments(consultationId);
    }

    /* =====================================================================
       Token-based methods (Pre-Join & Meeting Room flow)
       ===================================================================== */

    /**
     * Get consultation data by meetingToken — for Pre-Join page
     * Validates participant + time window (±30 min before, up to 2h after slot start)
     * @param {string} token - meetingToken UUID
     * @param {number} userId - Authenticated user's ID
     * @returns {Promise<object>} Consultation with full associations
     */
    async getConsultationByToken(token, userId) {
        const consultation = await consultationRepository.findByToken(token);

        if (!consultation) {
            const err = new Error('Consultation not found or link is invalid');
            err.statusCode = 404;
            throw err;
        }

        // Participant validation
        const isPatient = consultation.appointment.patient.userId === userId;
        const isDoctor  = consultation.appointment.doctor.userId  === userId;
        if (!isPatient && !isDoctor) {
            const err = new Error('You are not a participant in this consultation');
            err.statusCode = 403;
            throw err;
        }

        // Time window check — applied to both VIDEO and EMAIL consultations
        const isEmailConsultation = Number(consultation.appointment.consultationType) === ConsultationType.EMAIL;
        const slot = consultation.appointment.slot;
        if (slot) {
            const [h, m] = slot.startTime.split(':').map(Number);
            const apptTime = new Date(slot.slotDate);
            apptTime.setHours(h, m, 0, 0);

            const diffMin = (new Date() - apptTime) / 60000; // positive = past, negative = future

            if (diffMin < -30) {
                const err = new Error(`Consultation room opens 30 minutes before your appointment at ${slot.startTime}`);
                err.statusCode = 403;
                throw err;
            }
            if (diffMin > 120) {
                const err = new Error('This consultation link has expired');
                err.statusCode = 410;
                throw err;
            }
        }

        return consultation;
    }

    /**
     * Join (or re-join) a consultation by token — for both patient and doctor
     * Sets status=ACTIVE and startedAt on first join (idempotent)
     * @param {string} token
     * @param {number} userId
     * @returns {Promise<object>} { consultation, joinInfo }
     */
    async joinConsultationByToken(token, userId) {
        const consultation = await this.getConsultationByToken(token, userId);

        if (consultation.status === ConsultationStatus.ENDED) {
            const err = new Error('This consultation has already ended');
            err.statusCode = 400;
            throw err;
        }

        // Mark ACTIVE + startedAt only on first join
        if (consultation.status === ConsultationStatus.SCHEDULED) {
            await consultationRepository.update(consultation.id, {
                status: ConsultationStatus.ACTIVE,
                startedAt: new Date()
            });
        }

        const isDoctor = consultation.appointment.doctor.userId === userId;
        const userObj  = isDoctor
            ? consultation.appointment.doctor.user
            : consultation.appointment.patient.user;

        // EMAIL consultations don't use Jitsi — return null joinInfo
        const isEmail = Number(consultation.appointment.consultationType) === ConsultationType.EMAIL;
        const joinInfo = isEmail ? null : jitsiService.buildJoinInfo(userObj, consultation);
        const updated  = await consultationRepository.findByToken(token);
        return { consultation: updated, joinInfo };
    }

    /**
     * End consultation by token (doctor only)
     * @param {string} token
     * @param {number} userId
     * @returns {Promise<object>} Updated consultation
     */
    async endConsultationByToken(token, userId) {
        const consultation = await consultationRepository.findByToken(token);

        if (!consultation) {
            const err = new Error('Consultation not found');
            err.statusCode = 404;
            throw err;
        }

        if (consultation.appointment.doctor.userId !== userId) {
            const err = new Error('Only the assigned doctor can end this consultation');
            err.statusCode = 403;
            throw err;
        }

        if (consultation.status === ConsultationStatus.ENDED) {
            return consultation; // idempotent
        }

        // Mark appointment as COMPLETED
        await appointmentRepository.updateAppointment(consultation.appointmentId, {
            status: AppointmentStatus.COMPLETED
        });

        return await consultationRepository.update(consultation.id, {
            status: ConsultationStatus.ENDED,
            endedAt: new Date()
        });
    }

    /**
     * Save doctor notes by token (doctor only)
     * @param {string} token
     * @param {number} userId
     * @param {string} notes
     * @returns {Promise<object>} Updated consultation
     */
    async saveNotesByToken(token, userId, notes) {
        const consultation = await consultationRepository.findByToken(token);

        if (!consultation) {
            const err = new Error('Consultation not found');
            err.statusCode = 404;
            throw err;
        }

        if (consultation.appointment.doctor.userId !== userId) {
            const err = new Error('Only the assigned doctor can save notes');
            err.statusCode = 403;
            throw err;
        }

        return await consultationRepository.update(consultation.id, { notes });
    }

    /**
     * Get all messages for a consultation by token
     */
    async getMessagesByToken(token, userId) {
        const consultation = await this.getConsultationByToken(token, userId);

        const messages = await ConsultationMessage.findAll({
            where: { consultationId: consultation.id },
            order: [['createdAt', 'ASC']]
        });

        return messages;
    }

    /**
     * Send a new message to an email consultation thread
     * @param {string} token 
     * @param {number} userId 
     * @param {string} messageText 
     */
    async sendMessageByToken(token, userId, messageText) {
        const consultation = await this.getConsultationByToken(token, userId);

        if (consultation.status === ConsultationStatus.ENDED) {
            const err = new Error('This consultation has ended, you cannot send messages.');
            err.statusCode = 400;
            throw err;
        }

        const isDoctor = consultation.appointment.doctor.userId === userId;
        const senderRole = isDoctor ? 'DOCTOR' : 'PATIENT';

        const message = await ConsultationMessage.create({
            consultationId: consultation.id,
            senderRole,
            senderId: userId,
            message: messageText
        });

        // If it was just scheduled, mark it active when a message is sent
        if (consultation.status === ConsultationStatus.SCHEDULED) {
            await consultationRepository.update(consultation.id, {
                status: ConsultationStatus.ACTIVE,
                startedAt: new Date()
            });
        }

        return message;
    }
}

module.exports = new ConsultationService();
